# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160828_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
