# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_category_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillintheblank',
            name='id_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
