# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_multiplechoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillintheblank',
            name='explanation',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='explanation',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
