# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20161009_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
